### ISSUE TITLE
send packet size can be large than mtu

### ISSUE THREAD

**Issue by witkeysa** [mnestratov/natflt#1]
In your code,packet large than MAX_ETHER_SIZE is dropped.but actually packet to send can be large than MAX_ETHER_SIZE ,and it's normal,expecially in using ftp .This can be a bug.
http://packetbomb.com/how-can-the-packet-size-be-greater-than-the-mtu/

**Comment by mnestratov** [comment]
Jumbo frames and LSO are not supported at the moment. You are welcome to participate in implementing it.

**Comment by mnestratov** [comment]
Not an issue nut rather a feature request
